import esbuild from "esbuild";
import { cp, mkdir } from "fs/promises";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source
*/
`;

const prod = process.argv[2] === "production";

async function syncReleaseArtifacts() {
	await mkdir("release", { recursive: true });
	await cp("main.js", "release/main.js");
	await cp("manifest.json", "release/manifest.json");
	await cp("styles.css", "release/styles.css");
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await syncReleaseArtifacts();
	process.exit(0);
} else {
	await context.watch();
}
